// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAou8-rnmLRd7up4I4jviuXaycrQBIUYbw',
    appId: '1:299576932149:web:25d09de51a019d1877be7c',
    messagingSenderId: '299576932149',
    projectId: 'foodapp-1a884',
    authDomain: 'foodapp-1a884.firebaseapp.com',
    databaseURL: 'https://foodapp-1a884-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-1a884.appspot.com',
    measurementId: 'G-XG8ZD2JFPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqign3fDw1CPG0zcvnhwnpucFSRbnz_BQ',
    appId: '1:299576932149:android:3bc01a402e238e5977be7c',
    messagingSenderId: '299576932149',
    projectId: 'foodapp-1a884',
    databaseURL: 'https://foodapp-1a884-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-1a884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdrpEDqbPPbyfps1zQgq1sfC8zhQP0K4',
    appId: '1:299576932149:ios:9ce3cd2f49577fdc77be7c',
    messagingSenderId: '299576932149',
    projectId: 'foodapp-1a884',
    databaseURL: 'https://foodapp-1a884-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-1a884.appspot.com',
    androidClientId: '299576932149-taoueldgms0sm9j7d8ua6s2pjs4f7cj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdrpEDqbPPbyfps1zQgq1sfC8zhQP0K4',
    appId: '1:299576932149:ios:9ce3cd2f49577fdc77be7c',
    messagingSenderId: '299576932149',
    projectId: 'foodapp-1a884',
    databaseURL: 'https://foodapp-1a884-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-1a884.appspot.com',
    androidClientId: '299576932149-taoueldgms0sm9j7d8ua6s2pjs4f7cj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp',
  );
}
